---
name: Apply - OpenTofu via ARC

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

jobs:
  test:
    name: Pre-commit Tests
    runs-on: arc-dind
    container: image-registry.openshift-image-registry.svc:5000/public-registry/terraform-runner:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Git as root
        run: git config --global --add safe.directory '*'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Copy SSH area
        run: cp -r /root/.ssh /github/home/

      - name: Run tests
        run: make test

  apply:
    name: OpenTofu Apply
    runs-on: arc-dind
    container: image-registry.openshift-image-registry.svc:5000/public-registry/terraform-runner:latest
    needs: [test]
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Git as root
        run: git config --global --add safe.directory '*'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Copy SSH area
        run: cp -r /root/.ssh /github/home/

      - name: OpenTofu Apply
        run: make apply
